baseURL = "https://signalsandstride.github.io/test/"
relativeURLs = false
canonifyURLs = true
title = "Signals & Stride"
author = "Giuseppe Torres"
copyright = "Open-source <a class=\"text-muted text-decoration-none\" href=\"https://github.com/filipecarneiro/hugo-bootstrap-theme/blob/main/LICENSE\">MIT</a> Licensed."

timeZone = 'Europe/London'

theme = "hugo-bootstrap-theme"

disableHugoGeneratorInject = true
enableRobotsTXT = true
#enableGitInfo = true
enableEmoji = true
#sectionPagesMenu = "main"
#googleAnalytics = "UA-1511XXXX-X"

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[taxonomies]
  tag = "tags"
  category = "categories"
  series = 'series'
  author = "authors"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[permalinks]
  post = "/post/:title/"
