[[main]]
name = "CASA"
url = ""
weight = 10

[[main]]
name = "About"
url = "about"
weight = 20
title = "Made with ❤️ by the Hugo Bootstrap Theme team"

[[main]]
identifier = "blog"
name = "Posts"
weight = 40

[[main]]
name = "All"
url = "post"
weight = 100
parent = "blog"

[[main]]
name = "Running"
url = "tags/running"
weight = 20
parent = "blog"

[[main]]
name = "Health"
url = "tags/health"
weight = 30
parent = "blog"

[[main]]
name = "Techies"
url = "tags/techies"
weight = 40
parent = "blog"

[[main]]
identifier = "docs"
name = "Docs"
url = "page"
weight = 50

[[social]]
  name = "Email"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-twitter'><use href='images/feather/feather-sprite.svg#mail'/></svg>"
  url = "mailto:name@example.com"
  weight = 20
  title = "Contact via Email"

[[social]]
  name = "Facebook"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-github'><use href='images/feather/feather-sprite.svg#facebook'/></svg>"
  url = "https://facebook.com/"
  weight = 40
  title = "Visit our Facebook page"


